#!/bin/bash

echo "Enter the name of the user you want to delete: "
read user_d
sudo passwd -l $user
echo "The user <$user_d> is now bloked"
sudo pgrep -u $user
if [$? = 0]; then
	echo "No program was launched by <$user_d>"
else
	sudo killall -KILL -u $user
	echo "All the programs launched by <$user_d> were killed"
fi
sudo userdel -r $user
echo "The user has been sucessfully delete"
